### ISSUE TITLE
Deprecated. Use: Unbuff from jTOS Addon Manager.

### ISSUE THREAD

**Issue by TheIgni** [librarianrabbit/tos-addons#1]
Greetings,

In some of your addons you keep mentioning that you would rather have people use the Unbuff addon.

There seems to be no way of finding it however. I would really appreciate if you could redirect me to where i can find it. I'm playing a lot of my Kino-Featherfoot lately and being able to remove Skills that hinder me at times like Telekinesis & Levitation would be a blessing

**Comment by rfsc-mori** [comment]
Use the new jTOS manager:
https://github.com/JTosAddon/Tree-of-Savior-Addon-Manager/

The addon is there.

**Comment by kitsukannabi** [comment]
i'm already running the mod of the manager, all the addons from IToS are working great, but in the tab of JToS, it's not showing anything, i am doing something wrong? or it's just for JToS? sorry to ask this to you, but you seem active in GitHub.

**Comment by fdalex** [comment]
Hi !
I downloaded the lastest version of addon manager, but can't find this "unbuff" addon in the list. Any clue ? Your addon "remove summon" was so great for my sorcerer ^^ !

**Comment by rfsc-mori** [comment]
@fdalex, @kitsukannabi sorry for taking years to answer >.<

Did you get it working? Do you still need some help on fixing that? Are you sure that you're using the JTOS Addon Manager?

Can you try to follow this guide that a friend made?
https://docs.google.com/document/d/1y-SDK8r9pLfJgmWPmwMFqQbRjbZkquyuIGWFukH-61c/

**Comment by fdalex** [comment]
Hi ! Better to have a reply than no reply :D 
I totally gave up on the thing but you'r giving me a new hope ! I'll check your guide tonight. Thx !
