### ISSUE TITLE
Addon error

### ISSUE THREAD

**Issue by Draminha** [librarianrabbit/tos-addons#3]
I can't install
Card Buff Duration:

Failed to install addon. Please contact librarianrabbit.

**Comment by wesleyjr01** [comment]
I would like to know how to fix it too.

**Comment by rfsc-mori** [comment]
Just install Muteki2 from JTOS Addon Manager.

It adds more features than mine. I left it there in the case some users needed to uninstall it. I am removing the deprecated ones from my list now.
